if(NOT DEFINED ENV{SERIAL_TOOL})
  message(FATAL_ERROR "SERIAL_TOOL is not set")
endif()
if(NOT DEFINED ENV{SERIAL_PORT})
  message(FATAL_ERROR "SERIAL_PORT is not set")
endif()
if(NOT DEFINED ENV{SERIAL_BAUD})
  message(FATAL_ERROR "SERIAL_BAUD is not set")
endif()

set(_tool "$ENV{SERIAL_TOOL}")
set(_port "$ENV{SERIAL_PORT}")
set(_baud "$ENV{SERIAL_BAUD}")

if(_tool STREQUAL "stty")
  execute_process(COMMAND stty -F ${_port} ${_baud} raw -echo)
  execute_process(COMMAND cat ${_port})
elseif(_tool STREQUAL "screen")
  execute_process(COMMAND screen ${_port} ${_baud})
elseif(_tool STREQUAL "picocom")
  execute_process(COMMAND picocom -b ${_baud} ${_port})
elseif(_tool STREQUAL "miniterm")
  execute_process(COMMAND python3 -m serial.tools.miniterm ${_port} ${_baud})
else()
  message(FATAL_ERROR "Unsupported SERIAL_TOOL: ${_tool}")
endif()
